from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField, SelectField
from wtforms.validators import DataRequired, Length

class Query(FlaskForm):
    search  = StringField('query' )
    submit = SubmitField('Search')
    checkbox_title = BooleanField('title : ')
    checkbox_director = BooleanField('Director : ')
    select_genre = SelectField('Genre : ',choices = [('None','None'),('drama', 'drama'), ('comedy', 'comedy'), ('unknown', 'unknown'), ('action', 'action'), ('romance', 'romance'), ('thriller', 'thriller'), ('crime', 'crime'), ('horror', 'horror'), ('western', 'western'), ('musical', 'musical'), ('adventure', 'adventure'), ('romantic', 'romantic'), ('family', 'family'), ('war', 'war'), ('science', 'science'), ('fiction', 'fiction'), ('film', 'film'), ('fantasy', 'fantasy'), ('mystery', 'mystery'), ('animated', 'animated'), ('fi', 'fi'), ('sci', 'sci'), ('noir', 'noir'), ('animation', 'animation'), ('biography', 'biography'), ('short', 'short'), ('historical', 'historical'), ('social', 'social'), ('suspense', 'suspense'), ('anime', 'anime'), ('spy', 'spy'), ('sports', 'sports'), ('martial', 'martial'), ('arts', 'arts'), ('world', 'world'), ('documentary', 'documentary'), ('ii', 'ii'), ('biopic', 'biopic'), ('serial', 'serial'), ('superhero', 'superhero'), ('black', 'black'), ('political', 'political'), ('costume', 'costume'), ('biographical', 'biographical'), ('melodrama', 'melodrama'), ('tokusatsu', 'tokusatsu'), ('masala', 'masala'), ('supernatural', 'supernatural'), ('epic', 'epic'), ('psychological', 'psychological'), ('of', 'of'), ('adult', 'adult'), ('dramedy', 'dramedy'), ('mockumentary', 'mockumentary'), ('satire', 'satire'), ('disaster', 'disaster'), ('teen', 'teen'), ('history', 'history'), ('period', 'period'), ('children', 'children'), ("children's", "children's"), ('fu', 'fu'), ('the', 'the'), ('board', 'board'), ('mythology', 'mythology'), ('national', 'national'), ('kung', 'kung'), ('dark', 'dark'), ('parody', 'parody'), ('bio', 'bio'), ('erotic', 'erotic'), ('literary', 'literary'), ('life', 'life'), ('pic', 'pic'), ('slasher', 'slasher'), ('slice', 'slice'), ('com', 'com'), ('dance', 'dance'), ('devotional', 'devotional'), ('propaganda', 'propaganda'), ('rom', 'rom'), ('subject', 'subject'), ('youth', 'youth'), ('docudrama', 'docudrama'), ('feature', 'feature'), ('anthology', 'anthology'), ('by', 'by'), ('folklore', 'folklore'), ('kaiju', 'kaiju'), ('music', 'music'), ('on', 'on'), ('superheroes', 'superheroes'), ('wuxia', 'wuxia'), ('sex', 'sex'), ('based', 'based'), ('slapstick', 'slapstick'), ('detective', 'detective'), ('exploitation', 'exploitation'), ('gangster', 'gangster'), ('love', 'love')])
    checkbox_plot = BooleanField('Plot: ')
class Category(FlaskForm):
    checkbox = BooleanField('title')
